/ genparams.q - the parameter reference pages of the di.* modules, generated
/ from each module's describe[] and the shipped configuration files:
/   q genparams.q -q        (from the repository root, or make params)
/ writes di/simtick/docs/parameters.md, di/simmarket/docs/parameters.md
/ and di/simorder/docs/parameters.md

simtick:use`di.simtick
simmarket:use`di.simmarket
simorder:use`di.simorder

typename:`S`F`J`B`D`U`P`SL`FL`JL!("symbol";"float";"long";"boolean";"date";"minute";"timestamp";"symbol list";"float list";"long list")

shown:{[v]
  / a value as it is written in a file or at the q prompt
  $[10h=type v; v;
    -11h=type v; string v;
    11h=type v; " " sv string v;
    0h<type v; " " sv string v;
    -1h=type v; $[v;"1b";"0b"];
    string v]
  };

row:{[vals;r]
  / one table row of a describe[] row r, with its value in vals when it has one
  v:$[r[`param] in key vals; .z.m.shown vals r`param; ""];
  "| `",string[r`param],"` | ",typename[`$r`typ]," | ",r[`description]," | ",v," |"
  };

table:{[vals;t]
  ("| Parameter | Type | Description | Shipped value |";"|---|---|---|---|"),row[vals] each t
  };

section:{[vals;title;t] (enlist "### ",title),(enlist ""),table[vals;t],enlist ""};

f:simtick.files[]
market:simtick.loadmarket f`market
instruments:simtick.loadinstruments f`instruments
scenarios:simtick.loadscenarios f`scenarios
none:(`symbol$())!()
nvda:simtick.compose[market;instruments`NVDA;scenarios`normal;none]
tick:simtick.describe[]

/ ---------------------------------------------------------------- simtick
groups:`session`arrivals`auctions`sizes`quotes`trades`impact
lines:enlist "# di.simtick parameters"
lines,:enlist ""
lines,:enlist "Generated by `genparams.q` from `simtick.describe[]`; the shipped values are those of NVDA on the US large-cap market and the normal scenario (`simtick.compose` of the files in `di/simconfig`). Do not edit by hand: run `make params`."
lines,:enlist ""
lines,:enlist "A run reads a flat dictionary composed from four layers: the **market** file (how a market works), an **instrument** row (what makes a stock itself), a **scenario** row (what makes a day type) and the **run** dictionary (what changes between two runs). A later layer overrides an earlier one; an instrument row may override any market key. `baseintensity` is derived by `compose` from `tradesperday`."
lines,:enlist ""
lines,:enlist "## Instrument: the essential five"
lines,:enlist ""
lines,:enlist "Set on the instrument row (`di/simconfig/instruments.csv`) or given to `simtick.quick` with the date."
lines,:enlist ""
lines,:table[nvda;select from tick where layer=`essential]
lines,:enlist ""
lines,:enlist "## Market (`di/simconfig/markets/us_largecap.json`)"
lines,:enlist ""
lines,:enlist "Grouped as in the file. An instrument row may override any of these (XOM and PG override `spreadticks` and `primaryvenue`). The `orders` group is read by `di.simorder` and listed on its page."
lines,:enlist ""
lines,:raze {[vals;t;g] section[vals;string g;?[t;((=;`layer;enlist `market);(=;`group;enlist g));0b;()]]}[nvda;tick] each groups
lines,:enlist "## Scenario (`di/simconfig/scenarios.csv`)"
lines,:enlist ""
lines,:enlist "One row per day type: `normal`, `volatile`, `jumpy`. The multipliers are applied once by `compose` (then 1). The days group is read by `di.simmarket`."
lines,:enlist ""
lines,:section[nvda;"scenario";?[tick;((=;`layer;enlist `scenario);(=;`group;enlist `scenario));0b;()]]
lines,:section[nvda;"days (di.simmarket)";?[tick;((=;`layer;enlist `scenario);(=;`group;enlist `days));0b;()]]
lines,:enlist "## Run"
lines,:enlist ""
lines,:enlist "A dictionary with any of these; the market file's `run` group carries the defaults."
lines,:enlist ""
lines,:table[nvda;select from tick where layer=`run]
lines,:enlist ""
lines,:enlist "## Derived"
lines,:enlist ""
lines,:table[nvda;select from tick where layer=`derived]
`:di/simtick/docs/parameters.md 0: lines

/ ------------------------------------------------------------ simmarket
lines:enlist "# di.simmarket parameters"
lines,:enlist ""
lines,:enlist "Generated by `genparams.q` from `simmarket.describe[]`. Do not edit by hand: run `make params`."
lines,:enlist ""
lines,:enlist "The calendar keys belong to the scenario layer of `di.simtick`'s configuration (`di/simconfig/scenarios.csv`); a run takes a configuration composed by `simtick.compose` (or `simmarket.compose` for several instruments). The shipped values are the `normal` scenario's; `volatile` has persistence 0.8, correlation 0.8 and spreads 0.6."
lines,:enlist ""
lines,:table[nvda;simmarket.describe[]]
lines,:enlist ""
lines,:enlist "The calendar itself (a date list or a table with `date`, `closingtime`, `volmult`, `volumemult`, `jumpintensity`) is described in the module README."
system "mkdir -p di/simmarket/docs"
`:di/simmarket/docs/parameters.md 0: lines

/ --------------------------------------------------------------- simorder
of:simorder.files[]
orders:simorder.loadorders of`orders
good:simorder.compose[market;orders`good]
ord:simorder.describe[]
lines:enlist "# di.simorder parameters"
lines,:enlist ""
lines,:enlist "Generated by `genparams.q` from `simorder.describe[]`; the shipped values are those of the `good` order row composed with the US large-cap market file. Do not edit by hand: run `make params`."
lines,:enlist ""
lines,:enlist "An order's configuration is composed from the market file's `orders` group (and its `ticksize`) and an order row (`di/simconfig/orders.csv`); a row may override any market key. `urgency` and `maxpct` are read for arrival pacing only."
lines,:enlist ""
lines,:enlist "## Order row"
lines,:enlist ""
lines,:table[good;select from ord where layer in `essential`order`optional]
lines,:enlist ""
lines,:enlist "## From the market file"
lines,:enlist ""
lines,:table[good;select from ord where (layer=`market)&param in key simorder.schema]
lines,:enlist ""
lines,:enlist "## Market file: algo menu, order-flow defaults and impact"
lines,:enlist ""
lines,:enlist "Read by `simorder.generate` (any spec key overrides the market's) and `simorder.impactcfg`."
lines,:enlist ""
lines,:table[market;select from ord where not param in key simorder.schema]
system "mkdir -p di/simorder/docs"
`:di/simorder/docs/parameters.md 0: lines
-1 "parameter pages written";
exit 0
